/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UpdateDataProcessingAgreement.h"

namespace mydatamyconsent {
namespace models {




UpdateDataProcessingAgreement::UpdateDataProcessingAgreement()
{
    m_Version = utility::conversions::to_string_t("");
    m_VersionIsSet = false;
    m_Body = utility::conversions::to_string_t("");
    m_BodyIsSet = false;
    m_AttachmentUrl = utility::conversions::to_string_t("");
    m_AttachmentUrlIsSet = false;
}

UpdateDataProcessingAgreement::~UpdateDataProcessingAgreement()
{
}

void UpdateDataProcessingAgreement::validate()
{
    // TODO: implement validation
}

web::json::value UpdateDataProcessingAgreement::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_VersionIsSet)
    {
        val[utility::conversions::to_string_t(U("version"))] = ModelBase::toJson(m_Version);
    }
    if(m_BodyIsSet)
    {
        val[utility::conversions::to_string_t(U("body"))] = ModelBase::toJson(m_Body);
    }
    if(m_AttachmentUrlIsSet)
    {
        val[utility::conversions::to_string_t(U("attachmentUrl"))] = ModelBase::toJson(m_AttachmentUrl);
    }

    return val;
}

bool UpdateDataProcessingAgreement::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("version")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_version;
            ok &= ModelBase::fromJson(fieldValue, refVal_version);
            setVersion(refVal_version);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_body;
            ok &= ModelBase::fromJson(fieldValue, refVal_body);
            setBody(refVal_body);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("attachmentUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("attachmentUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_attachmentUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_attachmentUrl);
            setAttachmentUrl(refVal_attachmentUrl);
        }
    }
    return ok;
}

void UpdateDataProcessingAgreement::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("version")), m_Version));
    }
    if(m_BodyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("body")), m_Body));
    }
    if(m_AttachmentUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("attachmentUrl")), m_AttachmentUrl));
    }
}

bool UpdateDataProcessingAgreement::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("version"))))
    {
        utility::string_t refVal_version;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("version"))), refVal_version );
        setVersion(refVal_version);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("body"))))
    {
        utility::string_t refVal_body;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("body"))), refVal_body );
        setBody(refVal_body);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("attachmentUrl"))))
    {
        utility::string_t refVal_attachmentUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("attachmentUrl"))), refVal_attachmentUrl );
        setAttachmentUrl(refVal_attachmentUrl);
    }
    return ok;
}

utility::string_t UpdateDataProcessingAgreement::getVersion() const
{
    return m_Version;
}

void UpdateDataProcessingAgreement::setVersion(const utility::string_t& value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool UpdateDataProcessingAgreement::versionIsSet() const
{
    return m_VersionIsSet;
}

void UpdateDataProcessingAgreement::unsetVersion()
{
    m_VersionIsSet = false;
}
utility::string_t UpdateDataProcessingAgreement::getBody() const
{
    return m_Body;
}

void UpdateDataProcessingAgreement::setBody(const utility::string_t& value)
{
    m_Body = value;
    m_BodyIsSet = true;
}

bool UpdateDataProcessingAgreement::bodyIsSet() const
{
    return m_BodyIsSet;
}

void UpdateDataProcessingAgreement::unsetBody()
{
    m_BodyIsSet = false;
}
utility::string_t UpdateDataProcessingAgreement::getAttachmentUrl() const
{
    return m_AttachmentUrl;
}

void UpdateDataProcessingAgreement::setAttachmentUrl(const utility::string_t& value)
{
    m_AttachmentUrl = value;
    m_AttachmentUrlIsSet = true;
}

bool UpdateDataProcessingAgreement::attachmentUrlIsSet() const
{
    return m_AttachmentUrlIsSet;
}

void UpdateDataProcessingAgreement::unsetAttachmentUrl()
{
    m_AttachmentUrlIsSet = false;
}
}
}


